- name: create application directory
  file:
    path: "{{ server_root}}/{{ app_name }}"
    state: directory

# - name: create logs directory
#   file:
#     path: /var/www/httpd-logs
#     state: directory

- name: change ownership of a directory
  file:
    path: "{{ server_root}}/{{ app_name }}"
    state: directory
    recurse: yes
    owner: www-root
    group: www-root
