- name: add virtual host
  copy:
    src: ../files/test-realty.realtycrm.pro
    dest:  /etc/httpd/conf/vhosts/www-root/test-realty.realtycrm.pro
  notify: restart apache

# - name: Add vhost symlink in sites-enabled.
#   file:
#     src: /etc/apache2/sites-available/landing.estrella.ru.conf
#     dest: /etc/apache2/sites-enabled/landing.estrella.ru.conf
#     state: link
#   notify: restart apache

- name: Ensure Apache running
  service: name=httpd state=started enabled=yes

