
- name: Create database user with all database privileges
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass}}"
    priv: '*.*:ALL'
    state: present

- name: Create databases 
  mysql_db:
    login_user: "{{ db_user }}"
    login_password: "{{ db_pass }}"
    name: "{{db_name}}"
    state: present
