# Example clone a repo with separate git directory
- name: clone project from git
  git:
    repo: "{{ app_repo }}"
    dest: "{{ server_root }}/{{ app_name }}"

- name: install dependencies from composer
  composer:
    command: install
    working_dir: "{{ server_root }}/{{ app_name }}"

- name: copy common config
  template:
    src: main-local.php.j2
    dest:  "{{ server_root }}/{{ app_name }}/common/config/main-local.php"

- name: copy application console config
  copy:
    src: ../files/main-local.php
    dest:  "{{ server_root }}/{{ app_name }}/console/config/main-local.php"

- name: copy application console params
  copy:
    src: ../files/params-local.php
    dest:  "{{ server_root }}/{{ app_name }}/console/config/params-local.php"

- name: "{{ app_name }} | adjust directory ownership"
  file:
    path: "{{ server_root}}/{{ app_name }}"
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    recurse: yes

- name: execute migrations 
  shell: yes | php yii migrate
  args:
    chdir: "{{ server_root }}/{{ app_name }}"


- name: Recursively change ownership of a directory
  file:
    path: "{{ server_root }}/{{ app_name }}/{{ app_root }}"
    state: directory
    recurse: yes
    mode: 0755

- name: Recursively change ownership of a directory
  file:
    path: "{{ server_root }}/{{ app_name }}/{{ app_root }}/index.php"
    state: directory
    recurse: yes
    mode: 0777

