# Example clone a repo with separate git directory
- name: clone project from git
  git:
    repo: https://Bazilevs492@bitbucket.org/Bazilevs492/realty.estdev.ru.git
    dest: /var/www/www-root/data/www/test-realty.realtycrm.pro

- name: install dependencies from composer
  composer:
    command: install
    working_dir: /path/to/project


    
